# Generated by Django 4.1.2 on 2022-10-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=50)),
                ('airHumidity', models.CharField(max_length=10)),
                ('soilMoisture', models.CharField(max_length=10)),
                ('sunLight', models.CharField(max_length=10)),
            ],
        ),
    ]
